---
title: "p8105_hw4_sl4283_p2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# get started
library(tidyverse)
library(janitor)
library(haven)
library(ggridges)
library(ggthemes)
library(lubridate)
options(tibble.print_min = 3)
```

```{r}
# load and tidy the data
month_data = read_csv("./pols-month.csv") %>%
  clean_names() %>%
  mutate(date = floor_date(mon,"month"))

gdp_data = read_csv("./GDP.csv") %>%
  clean_names() %>%
  mutate(date = floor_date(date,"month"))

# Combine the data in pols-month.csv and GDP.csv based on the date 
join_data = left_join(month_data, gdp_data, by = "date") %>%
  mutate(value = as.numeric(value)) %>%
  filter(!is.na(value)) %>%
  mutate(prez_dem = as.character(prez_dem),
         prez_dem = replace(prez_dem, prez_dem == "1", "dem"), 
         prez_dem = replace(prez_dem, prez_dem == "0", "gop"))%>%

  ggplot(aes(x=date, y = value, color = prez_dem))+geom_bar(stat = "identity", fill="white")
join_data
```

**As we can see from the plot that two parties' GDP values increased during 1948-1980 and decreased after 1980. The type of party would change about every ten years. In 1940-1950, the values of GDP are highest when presidens were from the democratic party. The avrage values of democratic were higer than average values of the Republican Party.**